### ISSUE TITLE
Segmentation fault with sig-1.pd example

### ISSUE THREAD

**Issue by ftesser** [grrrr/py#5]
Hello, 

I have built both flext and py using `./build.sh pd gcc` and I can successfully run the py examples that do not make use of DSP (e.g.: simple-1.pd).

When I try to run an example that make use of DSP like sig-1.pd I get a segmentation fault error.
I put below the back trace.

Any suggestion or hint to solve this issue?

``` gdb pd core 
GNU gdb (Ubuntu 7.10-1ubuntu2) 7.10
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
http://www.gnu.org/software/gdb/bugs/.
Find the GDB manual and other documentation resources online at:
http://www.gnu.org/software/gdb/documentation/.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from pd...(no debugging symbols found)...done.

warning: core file may not match specified executable file.
[New LWP 4097]
[New LWP 4106]
[New LWP 4110]
[New LWP 4109]
[New LWP 4112]
[New LWP 4117]
[New LWP 4107]
[New LWP 4119]
[New LWP 4105]
[New LWP 4111]
[New LWP 4108]
[New LWP 4118]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `pd sig-1.pd'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f84f24a97f2 in pydsp::NewBuffers() () from /usr/local/lib/pd/extra/py.pd_linux

[Current thread is 1 (Thread 0x7f84f6f33740 (LWP 4097))](gdb) bt
#0  0x00007f84f24a97f2 in pydsp::NewBuffers() () from /usr/local/lib/pd/extra/py.pd_linux
#1  0x00007f84f24a9a08 in pydsp::CbDsp() () from /usr/local/lib/pd/extra/py.pd_linux
#2  0x00007f84f24af96d in flext_dsp_multi::SetupDsp(_signal**) () from /usr/local/lib/pd/extra/py.pd_linux
#3  0x0000000000472241 in ?? ()
#4  0x000000000047277b in ?? ()
#5  0x00000000004739ae in ugen_done_graph ()
#6  0x00000000004138d7 in ?? ()
#7  0x000000000041395f in ?? ()
#8  0x000000000045d4c5 in binbuf_eval ()
#9  0x0000000000456879 in outlet_bang ()
#10 0x000000000045519c in pd_typedmess ()
#11 0x00000000004554f2 in pd_vmess ()
#12 0x000000000041518f in canvas_loadbangsubpatches ()
#13 0x000000000045519c in pd_typedmess ()
#14 0x00000000004554f2 in pd_vmess ()
#15 0x0000000000453a3e in pd_doloadbang ()
#16 0x000000000045e75a in glob_evalfile ()
#17 0x0000000000460f4b in ?? ()
#18 0x0000000000461eae in glob_initfromgui ()
#19 0x000000000045d4c5 in binbuf_eval ()
#20 0x0000000000464934 in socketreceiver_read ()
#21 0x0000000000463db5 in ?? ()
#22 0x0000000000460cc8 in m_mainloop ()
#23 0x00007f84f5d49ac0 in __libc_start_main (main=0x4125e0 <main>, argc=2, argv=0x7ffeca3ff408, init=<optimised out>, fini=<optimised out>, rtld_fini=<optimised out>,

```
stack_end=0x7ffeca3ff3f8) at libc-start.c:289
```
#24 0x0000000000412619 in _start ()

(gdb) 

```

```

**Comment by grrrr** [comment]
Hi, the py/pyext DSP functionality has been introduced and tested many versions of Pd ago. I can imagine that a few things have changed since. I do hope i get the time to reproduce the reported issue soon.

**Comment by fhchl** [comment]
I have the same issue. Would be cool to have signal support!
